### ISSUE TITLE
Missing dependency libp2p_pyrust

### ISSUE THREAD

**Issue by jingyunc** [anaskalt/fedra#6]
Hello @anaskalt,

Thanks for sharing fedra. However, I met an issue while running it:

File "fedra/network/handler.py", line 20, in <module>
    import libp2p_pyrust as libp2p

The libp2p_pyrust is missing from the git code, and I couldn't seem to pip install it.

Can you please advise how to solve this?

**Comment by anaskalt** [comment]
Hello @jingyunc ,

It is an external module from another separate project.
Right now because it is still in beta version it is private and I have not released it yet.
